# Server configuration
server:
  address: "localhost"              # Interface to bind to (default: localhost)
  port: 8080
  forward_endpoint_enabled: true    # Enable/disable the /forward endpoint (default: true)
  default_timeout: "10s"            # Default timeout for external requests (format: "10s", "1m30s", "2m")

# logging
logging:
  level: debug
  format: pretty


# Global CORS rules, applied to all responses.
cors:
  allow_origins: ["*"]
  allow_methods: "POST, GET, OPTIONS"
  allow_headers: "*"
  allow_credentials: false
  
endpoints:
  - 
    path: /
    remote_url: https://www.postb.in/1757247861343-6690988021437
    #timeout: "30s" # Optional: Override global default timeout for this endpoint
    headers: 
      - X-custom-header: "foo {{ ANY_ENV_VAR }}"
    query_params:
      - foo: root
  - 
    path: /forward
    remote_url: https://www.postb.in/1757247861343-6690988021437
    #timeout: "30s" # Optional: Override global default timeout for this endpoint
    headers: 
      - X-custom-header: "foo {{ ANY_ENV_VAR }}"
    query_params:
      - foo: bar
  - 
    path: /test
    remote_url: https://www.postb.in/1757247861343-6690988021437
    #timeout: "30s" # Optional: Override global default timeout for this endpoint
    headers: 
      - X-custom-header: "foo {{ ANY_ENV_VAR }}"
    query_params:
      - foo: bar
