name: Release

on:
  push:
    tags: [v*]

jobs:
  test:
    uses: ./.github/workflows/ci.yml

  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v5
      - 
        name: Semantic release
        uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'
      - 
        name: Build
        run: go build -v ./cmd -ldflags "-X main.version${{ github.ref_name[1:] }}" -o ./corsair 
      
      - 
        name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
          files: |
            corsair