name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v5
    - 
      name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25'
    - 
      name: Verify dependencies
      run: go mod verify
    - 
      name: Test
      run: go test -v ./...
