# Build & publish docker images
name: Docker

on:
  push:
    tags: [v*]

jobs:
  dockerhub:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Extract version
        run: |
          VERSION="${GITHUB_REF_NAME#v}"   # strip leading v
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - 
        name: Version
        run: echo ${VERSION}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            b4bz/corsair:latest
            b4bz/corsair:${{ env.VERSION }}
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ env.VERSION }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            VERSION=${{ env.VERSION }}