name: Release

on:
  push:
    tags: [v*]

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v5
      - 
        name: Semantic release
        uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'
      - 
        name: Verify dependencies
        run: go mod verify
      - 
        name: Test
        run: go test -v ./...
      - 
        name: Build
        run: |
          go build -v -o ./corsair -ldflags "-X main.version=${GITHUB_REF_NAME#v}" ./cmd/
      - 
        name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
          files: |
            corsair